### ISSUE TITLE
Events are working

### ISSUE THREAD

**Issue by kevinob11** [bevacqua/angular-dragula#1]
The event replication isn't working for me.

The following prints the element and container properly to my console:
```
    dragulaService.options($scope, 'drag', {
      containers: Array.prototype.slice.call(document.querySelectorAll('ul.schedule-list'))
    });

    dragulaService.find($scope, 'drag').drake.on('drop', function(el, drop, source) {
      console.log(el, 'el');
      console.log(drop, 'drop');
    });
```

While this does nothing:
```
    dragulaService.options($scope, 'drag', {
      containers: Array.prototype.slice.call(document.querySelectorAll('ul.schedule-list'))
    });

    $scope.$on('drag.drop', function(el, drop, source) {
      console.log(el, 'el');
      console.log(drop, 'drop');
    });
```

**Comment by bevacqua** [comment]
Check out the demo, they're working in the demo. Your listener for `$scope.$on` isn't taking the Angular `event` argument. Listener should have `(e, el, container, source)` arguments

**Comment by kevinob11** [comment]
The problem was that I was creating the bag using the dragulaService.options method, and was not using the directive. I chose to do it that way because the directive takes whatever the current scope is and sets up the bag on that scope. I was attempting to use it inside an ng-repeat so I could only drag internal to that item in the ng-repeat. It would be great if bags created via the options method similarly replicated events.

**Comment by bevacqua** [comment]
That's doable. Want to make a pr?

**Comment by kevinob11** [comment]
Sure, I probably won't have time today, but I'm happy to get one put together this week
