### ISSUE TITLE
Setting options causes exception on drop

### ISSUE THREAD

**Issue by kennethlynne** [bevacqua/angular-dragula#11]
Everything works OK, until I introduce this bit of code: 
```
      dragulaService.options($scope, 'rearrange', {
        moves: function (el, container, handle) {
          return true;
        }
      });
```
When something is dropped I get an exception.
![image](https://cloud.githubusercontent.com/assets/390817/9493300/ef41e09e-4bfe-11e5-8926-e62abd8e184b.png)

**Comment by bevacqua** [comment]
What does the html look like?

**Comment by kennethlynne** [comment]
```html
 <md-list 
           dragula="'rearrangeContent'"
           dragula-model="ctrl.items">

    <content-list-item-component
      ng-repeat="content in ctrl.items track by content.id"
      content="content">
    </content-list-item-component>

  </md-list>
```

**Comment by kennethlynne** [comment]
Btw ctrl.items is undefined to begin with, and eventually the content will be loaded async, related to #13 ?

**Comment by luckylooke** [comment]
@kennethlynne async is the problem, dragula expects model to be loaded on init. I can look at the code later if there is possible some simple solution. ;)

**Comment by kennethlynne** [comment]
I used ng-if on the wrapping element to work around it, but it is not optimal

**Comment by kennethlynne** [comment]
So that it is loaded only when the items are loaded

**Comment by j0k3r** [comment]
I got the same error.
Here is a jsfiddle that reprocude the bug: http://jsfiddle.net/j0k/20bk7vqL/

**Comment by joncys** [comment]
#17 solves this. The code got merged, but the new version has not yet been released. You can point to master from npm/bower for the time being.

**Comment by j0k3r** [comment]
@bevacqua any chance to tag `v1.0.13` with that fix ?
