### ISSUE TITLE
Event on model sync

### ISSUE THREAD

**Issue by DanielSchuech** [bevacqua/angular-dragula#12]
Hello,

at first thanks for the well working framework. Especially for the new feature of syncing the model via dragula-model.
I ve one problem. I would like to do some stuff after the sync of the model. The drop event isn´t helpful. On this event the model will be synced asychron. So the sync isn´t finished when i´m receiving the drop event.

Everyone who´s using the dragula-model can´t use the existing drop event. My advise would be to add an broadcast in the service.js after line 46.

Thanks,
Daniel

**Comment by kennethlynne** [comment]
+1

**Comment by bevacqua** [comment]
Can you make a PR to this effect?

**Comment by DanielSchuech** [comment]
Yes I will do it tomorrow

**Comment by DanielSchuech** [comment]
Any new updates about the topic?

**Comment by luckylooke** [comment]
merged ;)
