### ISSUE TITLE
Looses reference to model 

### ISSUE THREAD

**Issue by kennethlynne** [bevacqua/angular-dragula#13]
When one loads items that should be rearranged async, it will loose its reference to the model object, so that subsequent writes to the object passed in as a parameter to `dragula-model=""` is lost.

**Comment by bevacqua** [comment]
Can you look into this one?

**Comment by luckylooke** [comment]
@kennethlynne @bevacqua I dont understand the problem, maybe my english is not good enough.. could you describe it more, or can you make live demo somewhere? Thanks

**Comment by kennethlynne** [comment]
If you send a reference to a model to dragula, and then replace the reference:
```js
$scope.data = data;
```

It seems dragula will keep the reference to the old data, which may have been undefined at the time.
So when I then rearrange items, it does not update the new array.

**Comment by kennethlynne** [comment]
Adding an ng-if to the wrapping element so that dragula loads only when the content is loaded fixes the problem, but is not the optimal solution

**Comment by luckylooke** [comment]
Waht you can do here for now is instead of replacing whole model, just update it. Remove all inside ```$scope.data.length = 0``` and load new data ```Array.prototype.push.apply($scope.data, newData);```. We can also provide some interface for updating data or watchdog on ```dragula-model``` atribute, what do you think @bevacqua ?

**Comment by kennethlynne** [comment]
Thanks! I used ng-if on the wrapping element for now, but that is a better approach. 
We do modify the contents of the array after load (create new items and rearrange them), so I would love to have better support for that.

**Comment by bevacqua** [comment]
I think we should consider demanding that the user defines a `dragula-model`, drop regular events, and just emit after `model` changes are applied. #14
