### ISSUE TITLE
How to trigger drag after a delay - on touch and hold for x ms?

### ISSUE THREAD

**Issue by kennethlynne** [bevacqua/angular-dragula#15]
I need to be able to disable drag and only enable it when the user holds an item for x ms. What is the best way to achieve this?

**Comment by bevacqua** [comment]
You *should* be able to simply do

```js
var heldForThreeSeconds = 3000
var itemWasClicked
document.body.addEventListener('mousedown', function () {
  itemWasClicked = new Date()
})
dragula({
  moves: function () {
    return new Date() - itemWasClicked > heldForThreeSeconds
  }
}

**Comment by afifa-tehseen** [comment]
Hi, i am having the same issue and I don't really have much knowledge of JS I just attached this plugin with my HTML. I needed to know where did you put the above JS to solve this issue. thanks in advance.
