### ISSUE TITLE
Nested bags

### ISSUE THREAD

**Issue by minmur** [bevacqua/angular-dragula#19]
Hi.

I want to make a nested bags structure. Something like this: 
![Nested bags](http://3.1m.yt/3bozcRVzs.jpg)

As you can see items 12 and 80 are in one bag ("Parent") and items 25, 67 and 36 in other ("Child") which is inside item 12.
I also have overridden `moves` that dragging works when clicking on handle (as in example).

Drag and drop Parent's items works as expected, but when i try to move Child's item, item 12 starts dragging also.

Not sure if it's a bug or i'm doing something wrong. `scope.$emit.apply(scope, args);` in `replicateEvents` function looks suspicious for me: Child's item's click event event bubbles to the Parent's item. Maybe i'm wrong.

**Comment by luckylooke** [comment]
Maybe [this](https://github.com/bevacqua/dragula/issues/31) could help, if not, please provide live example so I can investigate in your enviroment. (you can use, jsfiddle, codepen, your website, whatever...). Thanks

**Comment by minmur** [comment]
Thanks for idea. It helped.
