### ISSUE TITLE
Can't scroll or zoom on iOS Safari

### ISSUE THREAD

**Issue by adouglas** [bevacqua/angular-dragula#2]
On http://bevacqua.github.io/angular-dragula I can drag and drop just fine in Safari but can't scroll the page or pinch to zoom. 

Versions
iOS: 8.4

**Comment by nobitagit** [comment]
On Android too, but yesterday it was working fine so I guess it's just the latest update that broke something in that sense.

**Comment by kennethlynne** [comment]
+1 (on android)

**Comment by bevacqua** [comment]
Yeah, 3.0.0 broke this. Working on a fix

**Comment by bevacqua** [comment]
Fixed in `angular-dragula@1.0.2` and `dragula@3.0.1`

**Comment by adouglas** [comment]
Works a treat, thanks!
