### ISSUE TITLE
Add option to enable/disable drag

### ISSUE THREAD

**Issue by benmarte** [bevacqua/angular-dragula#20]
I want to be able to enable/disable the drag functionality via an option parameter.

For example I want to make a toggle button that enables dragging when the user is in edit mode, so I will be able to do something like `dragula.options.enableDrag = true;` and enable the dragging and `dragula.options.enableDrag = false;` to disable it.

Thanks for this neat module.

**Comment by luckylooke** [comment]
You can achieve this behavior by setting move method in options.
```js
 {
   move: function(){
      return $scope.enableDrag;
   }
}
```

**Comment by forcewill** [comment]
Just a note 
Its *moves* and not *move*

**Comment by luckylooke** [comment]
@forcewill thanks... fixed ;)

**Comment by ldewez** [comment]
Can you give all the code to do that. When I try to implement it, the "moves" overrided method never be fired.

I use angular-dragula for drag and drop rows in table. I have 
`<tbody dragula="'{{ category.id }}'" dragula-model="category.products">
<tr ng-repeat="product in category.products">
...
</tr>
</tbody>`

In Controller if I do :
`angularDragula.options($scope, category.id, {
  moves: function() {
    console.log('moves');
    return false;
  }
});`
 I never see my console log and Drag and Drop continue working.

**Comment by Nexxado** [comment]
same here, the moves method doesn't fire
