### ISSUE TITLE
Use with mdGridList

### ISSUE THREAD

**Issue by jsmylnycky** [bevacqua/angular-dragula#21]
Hi,

I'm attempting to plug this into my Angular (1.4.5) project, which utilizes Angular Material (0.11.0).

```
<md-grid-list dragula="'bag-one'" dragula-scope="$parent"
                      md-gutter="30px"
                      md-cols-sm="1" md-cols-md="2" md-cols-gt-md="3"
                      md-row-height="135px">
```

Attempting to set dragula on the grid-list ends up throwing this error:

```
[$compile:multidir] Multiple directives [dragula, mdGridList (module: material.components.gridList)] asking for new/isolated scope on: <md-grid-list dragula="'bag-one'" dragula-scope="$parent" md-gutter="30px" md-cols-sm="1" md-cols-md="2" md-cols-gt-md="3" md-row-height="135px">
http://errors.angularjs.org/1.4.5/$compile/multidir?p0=dragula&p1=&p2=mdGridList&p3=%20(module%3A%20material.components.gridList)&p4=new%2Fisolated<div md-tabs-template="::tab.template" md-connected-if="tab.isActive()" md-scope="::tab.parent" ng-if="$mdTabsCtrl.enableDisconnect || tab.shouldRender()" class="ng-scope ng-isolate-scope">cope&p5=%3Cmd-grid-list%dragula%3D%22'bag-one'%22%20dragula-scope%3D%22%24parent%22%20md-gutter%3D%2230px%22%20md-cols-sm%3D%221%22%20md-cols-md%3D%222%22%20md-cols-gt-md%3D%223%22%20md-row-height%3D%22135px%22%3E
```

Has anyone successfully used this plugin with the gridlist?

Thanks

**Comment by luckylooke** [comment]
Probably the only way to solve this for now is to make it nested.
```html
<md-grid-list>
    <dragula>
        <md-cols>
    </>
</>
```
but this can lead gridlist into problems.
Separating angular-dragula from scope in future will solve it definitely.

**Comment by flex123** [comment]
I am trying to do the same thing without any luck.. I even tried luckylooke's suggestion.  Anyone else has used dragula with md-grid-list successfully?

**Comment by luckylooke** [comment]
If you provide live demo of problem (jsfiddle,jsbin,codepen,...) I will look into it. Thanks

**Comment by flex123** [comment]
Thanks luckylooke.  I got this demo on plunkr...  I added <dragula> and the grid list stopped working.


http://plnkr.co/edit/8HyY7HWinL7xVmVGZld1?p=preview

**Comment by luckylooke** [comment]
I think in this case, you cannot achieve satisfactory results until angular-dragula is tied to scope (It wont be in future). You may use another library or make custom ng-material directives.

PS: Sending my progress in [your plunker](http://plnkr.co/edit/QBgT2f7C4ziW1Hylpy5a?p=preview)

**Comment by flex123** [comment]
Thanks luckylooke... I really appreciate your help.

**Comment by jsmylnycky** [comment]
Thanks guys for the brainstorming :)

I'll be circling back around in my works project that utilizes this to see what kind of progress I can make in using dragula again.  I'll put in any PRs as necessary if I make any modifications for it to work.

**Comment by jaksiprejak** [comment]
Hello,

Did this issue ever get resolved, is it possible to use dragula with mdgridlist now?
