### ISSUE TITLE
using this without requireJS?

### ISSUE THREAD

**Issue by dgreene1** [bevacqua/angular-dragula#23]
The current [documentation](https://github.com/bevacqua/angular-dragula#setup) shows the use of require statements. I'm trying to keep my project to a minimum, so I'd rather not include requireJS.

Can you please describe how to include angular-dragula into my module?

**Comment by bevacqua** [comment]
Use the file in `dist`

**Comment by sachinchoolur** [comment]
> Use the file in dist

I have tried using `dist/angular-dragula.min.js` but it doesn't work for me. 
Do you have an example for this?

**Comment by felippenardi** [comment]
@bevacqua Dist files still has `require`, so we can not use it without requirejs.

I'm re-opening that issue here: https://github.com/bevacqua/angular-dragula/issues/37

**Comment by dgreene1** [comment]
@bevacqua I love your work, but can't you see that the documentation is unclear about how to use this without a UMD library?

**Comment by bevacqua** [comment]
Guys, please take a look at the index.html file. It doesn't use any libraries besides drop-in angular and angular-dragula, and it just works.
