### ISSUE TITLE
Cannot use dragula with angular 

### ISSUE THREAD

**Issue by rabr2ro** [bevacqua/angular-dragula#24]
I don't understand how should I initialize the dragula module.
I've tried
```
angular.module('app', [
 ...
'ui.router',
'dragula',
'ngMaterial',
'pascalprecht.translate',
...
]);
```
but it didn't work.

Then I've tried
```
angular.module('angular-dragula', [angularDragula(angular)]);
```
but it complains that 'angularDragula' is not defined.
Can you be more explicit than using the dist? Why this is not an angular module like all the others (material, translate, etc)?

**Comment by bevacqua** [comment]
Read the docs.

**Comment by vko-online** [comment]
That implementation sucks

**Comment by lammel** [comment]
Is there any particular reason why angular-dragula is not using the standard module syntax?

I would expect it to be loaded like this:

    angular.module('app', [
      'ngRoute',
      'angularDragula'
    ]);

**Comment by andynagai** [comment]
According to this doc: https://github.com/bevacqua/angular-dragula#setup

You are supposed to require() the file. AngularJS does not support require(). I keep getting require undefined error. The doc also says can install through bower. When installing through bower aren't you supposed to not use require?

**Comment by sankhaKarunasekara** [comment]
there is a problem with angularjs-dragula/angularjs-dragula.js file. instead use the angularjs-dragula/dist/angularjs-dragula.min.js file, you will be ok.
