### ISSUE TITLE
drop-model event is never fired when model data is loaded via a promise

### ISSUE THREAD

**Issue by jmaupetit** [bevacqua/angular-dragula#26]
Here is an example reproducing the bug: http://jsfiddle.net/mr0pear7/2/

Am I missing something?

**Comment by DanielSchuech** [comment]
Dragula catches the reference to $scope.users on the load of the page. After that you will request the json via http. You are linking $scope.users to another reference by the follwing command: 
```javascript
$scope.users = _.map(data, 'name');
```

What you need to do is creating an empty array on startup and just push all readed users.
I ve modified your fiddle that you can see it working: http://jsfiddle.net/zeoqz8ob/

The dargula model crashes when you are doing an assignment. If you want to fill it with complete new content you need to do it via clearing the array and push all new items:

```javascript
$scope.users.length = 0; //clears the array
newItemsArray.forEach(function(item) {
  $scope.users.push(item);
});
```

Greetings, Daniel

**Comment by luckylooke** [comment]
Thank you again @DanielSchuech, great answer! :+1:

**Comment by jmaupetit** [comment]
:+1: 

Works like a charm! Thank you for having taken the time to provide a detailed answer.
