### ISSUE TITLE
dragula-model issue with "dynamic" model

### ISSUE THREAD

**Issue by forcewill** [bevacqua/angular-dragula#27]
If we have a model index by a value that changes dynamically like 
dragula-model="tabs[selectedIdx]" in which the initial selectedIdx equals 0  then angular-dragula just won't work as expected, since changing selectedIdx to something other then 0 and doing drag and drop operations, those operations will still be made on index 0.

here is a fiddler http://jsfiddle.net/36meLf7r/

Add some items to the first tab, then select tab 1 again add some items, and one can see that no item will be added to the second tab going back to the tab 0 the items added while on tab 1 will be on tab 0 .

**Comment by DanielSchuech** [comment]
Thats a normal behavior. The dragula-model attribute will only be readed once on the load of the page. So it isn´t possible to do it in your way.

I ve changed your fiddle to fit your requirements: http://jsfiddle.net/692m740c/1/

The array that you ve given dragula via the dragula-model attribute needs to hold the reference which is declared on the startup. You need to save the done changes of the model and refill it with the items of the new selected tab.

Greetings, Daniel

**Comment by luckylooke** [comment]
Thank you @DanielSchuech, great answer! :+1:
