### ISSUE TITLE
Can't apply on the table rows <tr> which has ng-repeat.

### ISSUE THREAD

**Issue by ahmadalibaloch** [bevacqua/angular-dragula#28]
<table class="table container" show-filter="filter" dragula='"first-bag"' >
                <tr ng-repeat="item in data" ng-class="{'active': item.$selected}"  dragula-scope='$parent'>
                    <td table-index item="item" on-check=";" data-title="'#'"></td>

                    <td data-title="'Outward Code'" filter="{'Name':'text'}">
                        {{item.Name}}
                    </td>
                    <td data-title="'Country'" filter="{'Country':'text'}">
                        {{item.Country}}
                    </td>
                </tr>
        </table>

It starts dragging each of the TD instead of complete row.

**Comment by DanielSchuech** [comment]
It´s not possible for me to drag a td with your code snippet. You can just drag the whole table.

It´s a bit different in tables as in divs. It doesn´t work this way.
I would repeat the whole table. The dragula-scope isn´t needed in this case.
```javascript
<table class="table container" show-filter="filter" dragula='"first-bag"' ng-repeat="item in many">
            <tr ng-class="{'active': item.$selected}">
                <td table-index item="item" on-check=";" data-title="'#'"></td>

                <td data-title="'Outward Code'" filter="{'Name':'text'}">
                    {{item}}
                </td>
                <td data-title="'Country'" filter="{'Country':'text'}">
                    {{item}}
                </td>
            </tr>
    </table>
```

Also watch the following plnkr: http://plnkr.co/edit/2lSvS0YOuWAoFWaX4QZJ?p=preview

Greetings, Daniel

**Comment by ahmadalibaloch** [comment]
Great!. Thanks a lot for correction.

**Comment by veyselozdemir** [comment]
The corrected version generates a separate table for each row, which a bit defies the purpose. 
It is possible however to repeat the rows, while applying dragula container markup to a tbody element:  

```
<table border='1' class="table container" show-filter="filter" >
      <tbody dragula='"first-bag"'>
            <tr ng-repeat="item in many" ng-class="{'active': item.$selected}" >
                <td table-index item="item" on-check=";" data-title="'#'"></td>

                <td data-title="'Outward Code'" filter="{'Name':'text'}">
                    {{item}} a
                </td>
                <td data-title="'Country'" filter="{'Country':'text'}">
                    {{item}} b
                </td>
            </tr>
      </tbody>
    </table>
```

Please see: http://plnkr.co/edit/llcyu0g78P3M7Sero6lX?p=preview
