### ISSUE TITLE
Ng-repeat with search filter brings back the items from other div or "first:bag"

### ISSUE THREAD

**Issue by ahmadalibaloch** [bevacqua/angular-dragula#29]
Search by Outward Code: <input type="text" ng-model="search.Name">
        <div class='container' dragula='"first-bag"' style="border:1px solid gray;padding:10px;margin:10px">
            <div ng-repeat="owc in outWardCodes| filter:search | limitTo:5">{{owc.Name}} {{owc.Country}}</div>
        </div>
      <div dragula='"first-bag"'>
                <div>Make sure to check out the <a href='https://github.com/bevacqua/dragula#readme'>documentation on GitHub!</a></div>
        </div>

When I drag an element from ng-repeat dive to the below bag and search again it fetches the records from that div back into ng-repeat div.

**Comment by DanielSchuech** [comment]
Yes and I would say it´s right.

With the change of the filter the ng-repeat will be rerendered. With that code snippet you aren´t changing the outWardCodes Array by drag&drop.

What I think you want is the dragula-model synchronisation
```javascript
Search by Outward Code: <input type="text" ng-model="search">
<div class='container' dragula='"first-bag"' style="border:1px solid gray;padding:10px;margin:10px"
      dragula-model="many">
    <div ng-repeat="owc in many| filter:search | limitTo:5">{{owc}}</div>
</div>
<div dragula='"first-bag"'dragula-model="many2">
     <div>Make sure to check out the <a href='https://github.com/bevacqua/dragula#readme'>documentation on GitHub!</a></div>
 </div>
```

Have a look to this plnkr where I ve corrected your snippet: http://plnkr.co/edit/bKNeo9cyKyjY3GpJcIhY?p=preview

Greetings, Daniel

**Comment by ahmadalibaloch** [comment]
Again thanks. It works like a charm. :+1:

**Comment by Zerlono** [comment]
Currently you cannot drag item while the list is filtered. dragula becomes confused with the array index.
In the plunker example you can try to search for "t" and then drag and drop "them" from list. You will notice, that "Explore" will be moved instead.

**Comment by jozsi** [comment]
+1

**Comment by vatsalpande** [comment]
+1
Any help would be appreciated
