### ISSUE TITLE
Events won't get replicated if bag was setup using dragulaService

### ISSUE THREAD

**Issue by spukst3r** [bevacqua/angular-dragula#3]
You can check this by trying by adding this line to `ExampleCtrl` controller in the example.js:
```javascript
dragulaService.options($scope, 'second-bag', {});
```
after this events won't fire anymore.

**Comment by kevinob11** [comment]
This is because events aren't replicated for bags created by the service. The PR above is to resolve that. I'd love some feedback if you have some time.

**Comment by spukst3r** [comment]
This pr fixes the error for me, thank you!

**Comment by bevacqua** [comment]
Fixed in `1.0.5`
