### ISSUE TITLE
Different options for containers in same bag

### ISSUE THREAD

**Issue by donnes** [bevacqua/angular-dragula#32]
##### HTML
```
<div class="col-sm-6" dragula='"widgets-elements"' style="border:1px solid purple; padding: 10px;">
  <div style="padding: 5px; border: 1px solid red;">Widget 01</div>
  <div style="padding: 5px; border: 1px solid red;">Widget 02</div>
  <div style="padding: 5px; border: 1px solid red;">Widget 03</div>
</div>
<div class="col-sm-6" dragula='"widgets-container"' style="border:1px solid #000; padding: 10px;">
  <div style="padding: 5px; border: 1px solid red;">Widget 01</div>
  <div style="padding: 5px; border: 1px solid red;">Widget 02</div>
  <div style="padding: 5px; border: 1px solid red;">Widget 03</div>
</div>
```

##### JS
```
dragulaService.options($rootScope, 'widgets-elements', {
  copy: true
});
dragulaService.options($rootScope, 'widgets-container', {
  removeOnSpill: true
});
```

**Comment by luckylooke** [comment]
What do you expect and what it actually does? Could you provide also working example (plunker, jsfiddle, ... ), thanks! :)

**Comment by donnes** [comment]
Sorry I can't create a plunker cause I don't know how create this effect.

![sem titulo-1](https://cloud.githubusercontent.com/assets/9506146/11092947/58260378-886e-11e5-9230-3e48c48cc57f.jpg)

**Comment by luckylooke** [comment]
For now I think that it is not possible to have different options for containers in same bag. You may want to use [this solution](http://luckylooke.github.io/dragular/#/docs/exampleDifferentOptionsWithModel).

**Comment by donnes** [comment]
Ok, thanks for help Lucky. :D

**Comment by huazi111** [comment]
it has changed?? i can`t use http://luckylooke.github.io/dragular/#/docs/docsInstall document, and the drag-angular can`t use
