### ISSUE TITLE
dropIndex is off if the target container is the mirror container

### ISSUE THREAD

**Issue by deje1011** [bevacqua/angular-dragula#33]
In order to make nested css rules work while dragging, I use the drag/drop containers as mirror containers. That works fine, except for the dropIndex being off due to the fact that the mirror is still inside the target container when dropping the transit element. Possible fix:

```javascript
function domIndexOf(child, parent) {
      /*
            If the mirror container is the target container itself, the mirror is still inside the target when
            dropping the transit element. Thats why we have to make sure to ignore the mirror element here. 
      */
      var children = angular.element(parent).children().not('.gu-mirror');
      return Array.prototype.indexOf.call(children, child);
  }
```

Thank you for this great plugin by the way!

**Comment by bevacqua** [comment]
Mirror container isn't supposed to be a `dragula` container.

**Comment by deje1011** [comment]
Okay fair enough, it also leads to some other problems as I just noticed. Is there another way to keep nested css selectors working?

**Comment by bevacqua** [comment]
Sure, place the mirrors in a shared parent instead of directly inside the containers. Please use the slack support channel. See dragula#248
