### ISSUE TITLE
ng2-dragula

### ISSUE THREAD

**Issue by NathanWalker** [bevacqua/angular-dragula#36]
I would love to do a direct port of this library to Angular2 if that's alright with you?

Planning on the port taking place here:
https://github.com/valor-software/ng2-dragula

We can work together on it or if anyone else would like to help, let me know. :+1:

**Comment by luckylooke** [comment]
@bevacqua please answer this.

**Comment by NathanWalker** [comment]
@luckylooke @bevacqua I am proceeding with directly porting this to Angular2.

**Comment by bevacqua** [comment]
Sounds good to me

**Comment by NathanWalker** [comment]
@bevacqua @luckylooke this is complete here now https://github.com/valor-software/ng2-dragula/pull/2
It will be merged soon :+1: 

It's an exact port of this angular 1.x version to 2.x with an identical demo and api.

**Comment by NathanWalker** [comment]
this has now been officially published:
https://www.npmjs.com/package/ng2-dragula
