### ISSUE TITLE
Dragular can't be used without RequireJS—not even with files inside dist

### ISSUE THREAD

**Issue by felippenardi** [bevacqua/angular-dragula#37]
The files on dist folder are using requireJS, which makes it impossible to use in projects without it.

Can you generate a distribution version that doesn't use requireJS?

The file would have to assume `angular` variable is available for use—as it is common to see on other angular 3rd party modules.

**Comment by bevacqua** [comment]
It's umd, not just requirejs. Please don't reopen closed issues. You can use slack if you have any questions.Thanks!
