### ISSUE TITLE
AngularDragula doesnt work with meteor

### ISSUE THREAD

**Issue by a-lucas** [bevacqua/angular-dragula#40]
Hi, 

I copy pasted the js inside public/compatibility, and the file gets imported correctly.

Then in my app, I have : 

    console.log(window);
    console.log(window.angularDragula);

    angular.module('socially', [
     'angular-meteor',
     'ui.router',
     'accounts.ui',
     'angularUtils.directives.dirPagination',
     'uiGmapgoogle-maps',
     'ui.bootstrap',
     window.angularDragula(angular)
    ]);

Strangely enough, the first log shows that window has a property called angularDracula, and this is a register function taking angular as a parameter.
Although, the second console shows ```undefined```

I renamed the file 00-angular-dragula.js to make sure the file is loaded before the others.

I am thinking to refactor this AMD logic of yours, but this is a nightmare (for me) - as I only use require for node - and don't see the logic in this file.

**Comment by luckylooke** [comment]
Object window has the property because you are browsing current object not the snapshot from time console.log is called. So problem is that your script is executed before the angular-dragula script. If you use module bundling you need to require angular-dragula script at the top of app file.
