### ISSUE TITLE
Sourcemapping Interference

### ISSUE THREAD

**Issue by janewang** [bevacqua/angular-dragula#42]
Hi @bevacqua, you've included your own sourcemap on L1121 in dist/angular-dragula.js and it is interfering with our sourcemap. We'd suggest that you remove this sourcemap and allow the users to determine how they would like to build their own code.

**Comment by bevacqua** [comment]
If you want to build your own distribution you're welcome to compile [`angular-dragula`](https://github.com/bevacqua/angular-dragula/blob/master/angular-dragula.js) via `browserify` like [in the build task](https://github.com/bevacqua/angular-dragula/blob/master/package.json#L11).

**Comment by thetrevdev** [comment]
I second this.  We also receive issues with the sourcemaps if we concatenate this as a dependency.

**Comment by bevacqua** [comment]
Again, you're welcome to compile [`angular-dragula`](https://github.com/bevacqua/angular-dragula/blob/master/angular-dragula.js) via `browserify` like [in the build task](https://github.com/bevacqua/angular-dragula/blob/master/package.json#L11). The `dist` files aren't changing -- they only exist to provide convenience, they're not meant for advanced uses.

**Comment by thetrevdev** [comment]
Thats not a very good solution.  That is a process we would have to do on each version bump so we can try and get bug fixes.
Ideally we could bower install angular-dragula.  Concatenate our application and be good to go.  Instead we get a bundle that has an incorrect sourcemap when concatenated.  
*This being said I realize that concatenating scripts is not the right solution but its what our old legacy system uses. 
Manually removing the sourcemapping from the distributable for now.
