### ISSUE TITLE
No tests?

### ISSUE THREAD

**Issue by onlywei** [bevacqua/angular-dragula#44]
I just noticed this project has no unit tests. I know it's just supposed to be a wrapper around Dragula, which has coverage, but the `service.js` looks to me pretty large. Not having unit tests really decreases my confidence in using this.

A co-worker of mine recently noticed something broke when upgrading to version `1.2.0` from version `1.1.6`. The details of the error are irrelevant to this issue -- she may open a different issue about that. 

I'm just curious if there's something preventing the contributors of this project from writing unit tests for it? Or is everyone just too busy with other things?

**Comment by luckylooke** [comment]
"Or is everyone just too busy with other things?" correct, you may create tests if you have time. We will be happy about that! ;)
