### ISSUE TITLE
Dups When Removing Item and Adding to Bag

### ISSUE THREAD

**Issue by janewang** [bevacqua/angular-dragula#45]
version 1.2.0
When removing an item from one container to another, this error appears only in 1.2.0. Looks like item with key undefined is being added to the second collection
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: page in model. Duplicate key: undefined:undefined, Duplicate value: undefined

**Comment by luckylooke** [comment]
Could you provide live example please, thanks!

**Comment by janewang** [comment]
old dragula: http://plnkr.co/edit/KHBlBUTXU57l4VD79TmJ?p=preview
new dragula: http://plnkr.co/edit/7YJcQc43eKeSyx7zLh31?p=preview

**Comment by luckylooke** [comment]
@janewang thank you for your contribution :+1: , I have fixed this issue in 1.2.1.
