### ISSUE TITLE
Failed to removeChild when Removing Item and Adding to Bag

### ISSUE THREAD

**Issue by janewang** [bevacqua/angular-dragula#47]
Hi, thanks for fixing the earlier issue in 1.2.0. I think 1.2.1 may still have some existing issues that have not been entirely addressed.

old dragula: http://plnkr.co/edit/KHBlBUTXU57l4VD79TmJ?p=preview
dragula 1.2.1: http://plnkr.co/edit/XPgk4ImKFGu9Mu1PpAIo?p=preview

In dragula 1.2.1, please see that you can no longer reorder elements in bag 1. (Please verify ). Then drag an element from bag 1 to bag 2. Console Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by luckylooke** [comment]
Everything works fine in DEMO page.. so there is problem with plunker iframe enviroment. When I change 'body' to 'doc.body' in dragula.js, then it starts working. See here: http://plnkr.co/edit/NkfCkSM6b0QXtGdawSM2?p=preview

I will try to PR this change into dragula.js

Have a nice day :)

**Comment by luckylooke** [comment]
Successfully merged, thanks again for you contribution @janewang :+1:
