### ISSUE TITLE
bower copy conflicts with realmike33/angular-dragula

### ISSUE THREAD

**Issue by driannaude** [bevacqua/angular-dragula#5]
Hey man, was just in the neighbourhood, wanted to switch to bevacqua/angular-dragula, and event after cleaning my bower cache and uninstalling realmike33's version (it was great, but this has some scope management stuff I need) I found it still resolves to [http://github.com/realmike33/angular-dragula](http://github.com/realmike33/angular-dragula). When installing from the github repo however, it installed fine. Just a heads up in case you guys are collab-ing. It may be the proxy here too, but just in case it isn't I thought I'd let you know.

**Comment by driannaude** [comment]
My bad, I just realised I didn't read it properly... Feel like a bit of a knob now. :) I just realized it's

```bower install angular-dragula.js```

I think i need more coffee.

**Comment by bevacqua** [comment]
I've posted an issue on their repo to see if they'd be willing to transfer ownership of `angular-dragula` registration on Bower.

**Comment by bevacqua** [comment]
FWIW they graced us with the `angular-dragula` bower registry name, so you can now do `bower install angular-dragula`.

https://github.com/realmike33/angular-dragula/issues/2
