### ISSUE TITLE
Drop model

### ISSUE THREAD

**Issue by soniram** [bevacqua/angular-dragula#51]
I'm using angular-dragula to move "orders" from this container

            <md-list dragula="'bag-a'" dragula-model='vm.orders'>
                <md-list-item class="md-3-line md-long-text" ng-repeat="order in vm.orders">

to this
                    <div class="car-orders" dragula="'bag-a'" dragula-model="car.orders" layout="column">
                        <div ng-repeat="order in car.orders">

I cannot figure out how a can get access to "order" model and do things using the drop-model event.

        $scope.$on('bag-a.drop-model', function (el, target, source) {
/// do things with order and car here..........
            console.log(el, target, source);
        });
Any help ?

**Comment by soniram** [comment]
Sorry.. this is the second container

                    <div class="car-orders" dragula="'bag-a'" dragula-model="car.orders" layout="column">
                        <div ng-repeat="order in car.orders">

**Comment by DanielSchuech** [comment]
I am not sure if i ve understood your problem. Maybe provide a plunkr. It would be easier to have a look into it. Or maybe give some more info what you want to do.

The drop-moel event will be fired when the changes are finished in the given dragula model. You can then use your model to task you want to do.

**Comment by soniram** [comment]
I am using a list of objects as my model, which I set in the div using ng-repeat. When I drag an item from this list to another div, I would like to change/modify some property of the object that I dragged depending on the object that I dropped it ?

I inspected the model-drop event callback parameters (el, source, target) but I cannot find anything like "source.model"  (containing the object that I dragged) and "target.model" (containing the object that I dropped the source).

Does such a feature exist or I'm missing something ?

**Comment by DanielSchuech** [comment]
You will not get the source.model directly but you can detect it by yourself.

We will get the DOM Element of the dragged element. Through this we could determine the model:

```js
$scope.$on('another-bag.drop-model', function (el, target, source) {debugger
    var movedContent = target.contents()[0].data;
    var index = $scope.many2.indexOf(movedContent);
    
    //dropped item $scope.many2[index]
    //you can modify it here
    console.log('dragged ' + $scope.many2[index]);
  });
```

You can find it also in the following Plunkr: [click](https://plnkr.co/edit/vU6Gf0LrIFaWs19cRVyx?p=preview)

I know thats this exemple is really simple and it isn´t mostly the case that the model will be displayed directly. But you could gain other opportunities like setting id`s, classes or other attributes with a title of the model to determine the dropped model. I don´t know another solution yet.

**Comment by bevacqua** [comment]
Please ask on Slack. https://dragula-slackin.herokuapp.com/
