### ISSUE TITLE
Issue with custom directive

### ISSUE THREAD

**Issue by forcewill** [bevacqua/angular-dragula#52]
I have a custom angular template directive, with some html displaying some info,
now in that directive in the `link` function i do some initialization of my model, basically some defaults on the view. 
Now elsewhere on  my app, i present a list of items using angular-dragula
when i drag them to the other container (the one that will contain a list of items of my custom directive) everything works fine, the link function is called and the template is initialized only when i drag to the bottom if i drag to the top (when there is already an item on the list) or between items, the link function is not called and as such my template directive is not initialized.

**Comment by bevacqua** [comment]
Please ask on Slack. https://dragula-slackin.herokuapp.com/
