### ISSUE TITLE
Replicating the "Copying stuff from only one of the containers and sorting on the other one?" example

### ISSUE THREAD

**Issue by Parpeytz** [bevacqua/angular-dragula#53]
I am trying to replicate the functionality of the origin dragula example called `Copying stuff from only one of the containers and sorting on the other one? No problem!` in Angular.

I have looked through your code, but can't figure how to replicate it in Angular. Is it even possible with the two dropzones being the same bag?

**Comment by DanielSchuech** [comment]
I run into the similar problem a few days ago as i ve investigated another issue.
It is working perfectly when both container have the same bag. I ve the issue while nesting different abgs into each other.

I used this feature a year ago and will investigate if i ve done a fault or if there is a bug.

Maybe provide a plnkr with your conditions.

The support will be done in slack. So please post your conditions with your issue right [here](https://dragula.slack.com)

**Comment by Parpeytz** [comment]
How do I get an invitation to the Slack channel?

**Comment by bevacqua** [comment]
There's a link that reads "Join us on Slack" at the top of bevacqua.github.io/dragula
