### ISSUE TITLE
work with promises

### ISSUE THREAD

**Issue by Handresito** [bevacqua/angular-dragula#54]
I'm trying to modify the order of the elements of an array from a promise but i can't, anyone have an idea how to do this?

Thanks!

**Comment by DanielSchuech** [comment]
Support will be done in slack -> [Dragula Slack](dragula.slack.com)

Where is your problem. Maybe provide some code.

1) resolve the promise
2) order the array

**Comment by Handresito** [comment]
Controller:
Service.getUserMagazines().then(function(data){
$scope.many = data;
})

Html:
<div class='wrapper'>
            <div class='container' dragula='"another-bag"' dragula-model='many'>
                <div ng-repeat='text in many' ng-bind='text'></div>
            </div>
        </div>

I can see how the data visually changed, but if i inspect the array elements, the order of the elements doesn't changed.

**Comment by DanielSchuech** [comment]
Its working correctly here: [Plnkr](https://plnkr.co/edit/XIMebvf9lDLspr0jy51E?p=preview)

Provide a plnkr where it isn´t working.
