### ISSUE TITLE
css

### ISSUE THREAD

**Issue by jacksoncharles** [bevacqua/angular-dragula#55]
As far as I can tell the associated CSS is not included in the NPM module. Perhaps needs an update.

Many thanks for the work.

**Comment by bevacqua** [comment]
https://github.com/bevacqua/angular-dragula/blob/master/dist/dragula.css

**Comment by jacksoncharles** [comment]
Hi,

Thanks, I have the CSS. I have never written an NPM package before but I was merely pointing out the CSS was not part of an NPM install.
