### ISSUE TITLE
Keep original appearence

### ISSUE THREAD

**Issue by carrbrpoa** [bevacqua/angular-dragula#56]
Hello,

I have some divs in a board like parent div that when I drop them, their appearence is modified. See:

Before:
![tasks_before](https://cloud.githubusercontent.com/assets/10212618/13428019/7cb94dba-df96-11e5-8a3e-80293811bfe6.png)

After:
![tasks_after](https://cloud.githubusercontent.com/assets/10212618/13428025/871799d8-df96-11e5-8dd5-bf680390fd8e.png)

I dropped "Tarefa 8" to "Tarefa 7" place.

Something I can do about it? I wish do keep the original appearence, always.

**Comment by bevacqua** [comment]
Use Slack for support requests, you can join clicking the link in http://bevacqua.github.io/dragula
