### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by lfarrell** [bevacqua/angular-dragula#6]
First off, thanks for a very cool module.
Does the module work with minification? Minifying the code using standard Angular annotations to preserve dependency injection doesn't seem to work. Module works great if left un-minified.

Thanks,

Dean

**Comment by bevacqua** [comment]
I don't see why it wouldn't work, the `['dep', 'dep', ..., function () { ... }]` pattern is used everywhere

**Comment by lfarrell** [comment]
Thanks, you are correct. Needed to do this:
angular.module('test', ['ngRoute', 'ui.bootstrap', angularDragula(angular)])
Not this to build correctly.
angular.module('test', ['ngRoute', 'ui.bootstrap', 'angularDragula(angular)'])

Thanks again for a great project,

Dean
