### ISSUE TITLE
Drake containers get out of sync with models

### ISSUE THREAD

**Issue by tomismore** [bevacqua/angular-dragula#64]
Hey, thank you so much for this incredible tool. It's a joy to use.

I put together a drag and drop formbuilder in my Angular 1 application and it works very well. In addition to dragging in radio buttons, checkboxes, text inputs, etc, there are also sections that can be dragged in, which themselves contain dragula bags. 

For the most part, everything still works well. I assign each section that's dragged in a unique class (by timestamping it), and am therefore able to copy in many sections and multiple levels of hierarchy.

However, sometimes when dragging and dropping sections within the form area, the drake.models and drake.containers array seem to get out of sync, producing unexpected behavior. Specifically, drake.containers appears to retain old timestamped bags (the bags are re-classed whenever they're dropped), which no longer exist in the DOM--yet, even introducing code that removes those bags only seems to exacerbate the problem.

Have you encountered this before? Any advice for a better approach that might forestall this? Any help you can offer is very much appreciated.

Thank you again!

**Comment by kucharskimaciej** [comment]
How did you handle it eventually?

**Comment by tomismore** [comment]
We've actually made a number of small modifications to the angular-dragula wrapper. It's on my todo list to contribute.

Basically there was a missed edgecase where a dropped dragula-model didn't get dropped from the array of containers-- I'll look for the line today and post it

**Comment by tomismore** [comment]
In the register() function, add

`drake.containers.splice(modelIndex, 1, drake.containers.pop())`

below
`
        if (drake.models) {
          var modelIndex = oldValue ? drake.models.indexOf(oldValue) : -1;
          if (modelIndex >= 0) {
            drake.models.splice(modelIndex, 1, newValue);`

so that the full function reads

`function register (angular) {
  return ['dragulaService', function angularDragula (dragulaService) {
    return {
      restrict: 'A',
      scope: {
        dragulaScope: '=',
        dragulaModel: '='
      },
      link: link
    };

    function link (scope, elem, attrs) {
      var dragulaScope = scope.dragulaScope || scope.$parent;
      var container = elem[0];
      var name = scope.$eval(attrs.dragula);
      var drake;

      var bag = dragulaService.find(dragulaScope, name);
      if (bag) {
        drake = bag.drake;
        drake.containers.push(container);
      } else {
        drake = dragula({
          containers: [container]
        });
        dragulaService.add(dragulaScope, name, drake);
      }

      scope.$watch('dragulaModel', function (newValue, oldValue) {
        if (!newValue) {
          return;
        }

        if (drake.models) {
          var modelIndex = oldValue ? drake.models.indexOf(oldValue) : -1;
          if (modelIndex >= 0) {
            drake.models.splice(modelIndex, 1, newValue);
            drake.containers.splice(modelIndex, 1, drake.containers.pop())
          } else {
            drake.models.push(newValue);
          }
        } else {
          drake.models = [newValue];
        }

        dragulaService.handleModels(dragulaScope, drake);
      });
    }
  }];
}`

**Comment by ooboobay** [comment]
Thank you @thomascmost!  Would love to see this fix merged.
