### ISSUE TITLE
DOM and model array are not synced

### ISSUE THREAD

**Issue by luckylooke** [bevacqua/angular-dragula#7]
When I use your example with ngRepeat:
```js
function ($scope) {
    $scope.many = ['The', 'possibilities', 'are', 'endless!'];
  }
```
And I change order or remove some items..
How can I get updated 'many' array?

**Comment by bevacqua** [comment]
Do you want to work on this enhancement?

**Comment by luckylooke** [comment]
I can try.. I have one idea how it should be done without modifying dragula
lib itself.

**Comment by bevacqua** [comment]
Sounds awesome!

**Comment by luckylooke** [comment]
I have one dilema... how do you wish users to provide model to sync with?
```js
dragulaService.options(scope, name, options, model)
```
or?

**Comment by bevacqua** [comment]
I was thinking we probably should do something like a directive `dragula-model='foo'`, and `$eval` that on the `dragula-scope`.

**Comment by luckylooke** [comment]
ok, I have also problem with drake events.. I have put listeners in setOptions, but they are not fired.. do you have idea why? I know there is replicator but there can be more than one listener right?
```js
function setOptions (scope, name, options) {
      var bag = add(scope, name, dragula(options));
      if(model !== void 0){ // model to sync with (must have same structure as containers)
        var ctx = getOrCreateCtx(scope);
        var drake = bag.drake;
        console.log('drake', drake);
        drake.on('remove',function removeModel () {
          console.log('removeModel', arguments);
        });
        drake.on('cloned',function clonedModel () {
          console.log('clonedModel', arguments);
        });
        drake.on('drop',function dropModel () {
          console.log('dropModel', arguments);
        });
      }
    }
```

**Comment by bevacqua** [comment]
You should be able to attach as many event listeners as you'd like. If they're not firing maybe you're attaching the events to the wrong `drake`?

**Comment by luckylooke** [comment]
@bevacqua yes, that was the cause... I had typo in bag name ;)

**Comment by bevacqua** [comment]
Awesome! Glad you're working on this
