### ISSUE TITLE
Weird behaviour with copy (true) and ordering.

### ISSUE THREAD

**Issue by thiagosoeiro** [bevacqua/angular-dragula#82]
**How it should works:**
Able to copy items from left container to right container. 
Only right container should order items. 

**What's actually happening:**
Ordering is enabled for both containers.
Array gets messed up when ordering. _It displays duplicated items!_
Drop-model events also not firing with this code:
```

        $scope.$on('first-bag.drop-model', function (e, el, target, source) {
            console.log("testing", el);
        });
```

What am I doing wrong?

This is the code example:
https://embed.plnkr.co/11A5M9gfNrcjr1OtUBIo/

**Comment by thiagosoeiro** [comment]
Resolved.

**Comment by dylanspurgin** [comment]
@thiagosoeiro What was the resolution for this issue? I am having the same issue.
